using System.Collections.Generic;
using System.Text;
using System;

namespace Assets.Scripts.Architecture.CodeGeneration
{
    public class CodeGenerator
    {
        private const char NewLineSymbol = '\n';
        private const char TabulationSymbol = '\t';
        private const char SemicolonSymbol = ';';
        private const char OpenScope = '{';
        private const char CloseScope = '}';

        private static readonly Dictionary<int, string> s_tabulations;

        private readonly StringBuilder _codeBuilder;
        
        private int _depth = 0;

        static CodeGenerator()
        {
            s_tabulations = new Dictionary<int, string>()
            {
                { 0, "" },
            };
        }

        public CodeGenerator()
        {
            _codeBuilder = new StringBuilder();
            
            Initialize();
        }

        public CodeGenerator AppendLine(string codeLine, bool isEndCodeLine = true)
        {
            TryAddTabulationKeyValue();

            _codeBuilder.Append(s_tabulations[_depth])
                        .Append(codeLine);

            if (isEndCodeLine)
                _codeBuilder.Append(SemicolonSymbol);

            _codeBuilder.AppendLine();

            return this;
        }

        public CodeGenerator PlaceOpenScope()
        {
            if (_codeBuilder[^1] == NewLineSymbol)
                _codeBuilder.Append(s_tabulations[_depth]);

            _codeBuilder.Append(OpenScope)
                .AppendLine();

            _depth++;

            return this;
        }

        public CodeGenerator PlaceCloseScope()
        {
            _depth--;

            if (_codeBuilder[^1] == NewLineSymbol)
                _codeBuilder.Append(s_tabulations[_depth]);

            _codeBuilder.Append(CloseScope)
                .AppendLine();

            return this;
        }

        public string Build()
        {
            if (_depth > 0)
                throw new InvalidOperationException($"Depth should be zero, but was {_depth}.");

            return _codeBuilder.ToString();
        }

        public void Clear()
        {
            _codeBuilder.Clear();
            _depth = 0;

            Initialize();
        }

        private void Initialize()
        {
            _codeBuilder.AppendLine("// <auto-generated>")
                        .AppendLine($"//     This code was generated by a {nameof(CodeGenerator)} tool.")
                        .AppendLine("//")
                        .AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if")
                        .AppendLine("//     the code is regenerated.")
                        .AppendLine("// </auto-generated>");
        }

        private bool TryAddTabulationKeyValue()
        {
            if (s_tabulations.ContainsKey(_depth))
                return false;

            string previousTabulation = s_tabulations[_depth - 1];
            string currentTabulation = previousTabulation + TabulationSymbol;

            s_tabulations[_depth] = currentTabulation;

            return true;
        }
    }
}